-- DAM restructure migration
SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `nexled_dam` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `nexled_dam`;
DROP TABLE IF EXISTS `dam_asset_links`;
DROP TABLE IF EXISTS `dam_assets`;
DROP TABLE IF EXISTS `dam_folders`;
CREATE TABLE `dam_folders` (
  `folder_id` VARCHAR(255) NOT NULL,
  `parent_id` VARCHAR(255) NULL,
  `name` VARCHAR(80) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `scope` VARCHAR(32) NOT NULL DEFAULT 'root',
  `kind` VARCHAR(16) NOT NULL DEFAULT 'system',
  `is_system` TINYINT(1) NOT NULL DEFAULT 1,
  `can_upload` TINYINT(1) NOT NULL DEFAULT 0,
  `can_create_children` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`folder_id`),
  UNIQUE KEY `uq_path` (`path`),
  KEY `idx_parent` (`parent_id`),
  KEY `idx_scope` (`scope`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dam_assets` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `filename` VARCHAR(255) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `public_id` VARCHAR(255) NOT NULL,
  `folder_id` VARCHAR(255) NOT NULL,
  `resource_type` VARCHAR(20) NOT NULL DEFAULT 'image',
  `format` VARCHAR(20) NULL,
  `mime_type` VARCHAR(100) NULL,
  `bytes` INT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `secure_url` VARCHAR(500) NOT NULL,
  `thumbnail_url` VARCHAR(500) NULL,
  `kind` VARCHAR(64) NOT NULL,
  `tags` JSON NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_public_id` (`public_id`),
  KEY `idx_kind` (`kind`),
  KEY `idx_folder` (`folder_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dam_asset_links` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `asset_id` INT NOT NULL,
  `product_code` VARCHAR(64) NULL,
  `family_code` VARCHAR(20) NULL,
  `role` VARCHAR(64) NOT NULL,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `fk_dam_asset_links_asset` FOREIGN KEY (`asset_id`) REFERENCES `dam_assets` (`id`) ON DELETE CASCADE,
  UNIQUE KEY `uq_link` (`asset_id`, `product_code`, `family_code`, `role`),
  KEY `idx_product` (`product_code`, `role`),
  KEY `idx_family` (`family_code`, `role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `dam_folders` (`folder_id`,`parent_id`,`name`,`path`,`scope`,`kind`,`is_system`,`can_upload`,`can_create_children`,`sort_order`) VALUES
('nexled',NULL,'nexled','nexled','root','system',1,0,1,0),
('nexled/datasheet','nexled','datasheet','nexled/datasheet','datasheet','system',1,0,1,10),
('nexled/datasheet/packshots','nexled/datasheet','packshots','nexled/datasheet/packshots','datasheet','system',1,0,1,10),
('nexled/datasheet/packshots/20deg','nexled/datasheet/packshots','20deg','nexled/datasheet/packshots/20deg','datasheet','system',1,1,0,10),
('nexled/datasheet/packshots/45deg','nexled/datasheet/packshots','45deg','nexled/datasheet/packshots/45deg','datasheet','system',1,1,0,20),
('nexled/datasheet/packshots/2x55deg-lf','nexled/datasheet/packshots','2x55deg-lf','nexled/datasheet/packshots/2x55deg-lf','datasheet','system',1,1,0,30),
('nexled/datasheet/packshots/40deg','nexled/datasheet/packshots','40deg','nexled/datasheet/packshots/40deg','datasheet','system',1,1,0,40),
('nexled/datasheet/packshots/frost','nexled/datasheet/packshots','frost','nexled/datasheet/packshots/frost','datasheet','system',1,1,0,50),
('nexled/datasheet/packshots/frostc','nexled/datasheet/packshots','frostc','nexled/datasheet/packshots/frostc','datasheet','system',1,1,0,60),
('nexled/datasheet/packshots/clear','nexled/datasheet/packshots','clear','nexled/datasheet/packshots/clear','datasheet','system',1,1,0,70),
('nexled/datasheet/packshots/generic','nexled/datasheet/packshots','generic','nexled/datasheet/packshots/generic','datasheet','system',1,1,0,80),
('nexled/datasheet/packshots/clear-1','nexled/datasheet/packshots','clear-1','nexled/datasheet/packshots/clear-1','datasheet','system',1,1,0,90),
('nexled/datasheet/packshots/clear-2','nexled/datasheet/packshots','clear-2','nexled/datasheet/packshots/clear-2','datasheet','system',1,1,0,100),
('nexled/datasheet/packshots/clear-4','nexled/datasheet/packshots','clear-4','nexled/datasheet/packshots/clear-4','datasheet','system',1,1,0,110),
('nexled/datasheet/packshots/clear-5','nexled/datasheet/packshots','clear-5','nexled/datasheet/packshots/clear-5','datasheet','system',1,1,0,120),
('nexled/datasheet/packshots/clear-6','nexled/datasheet/packshots','clear-6','nexled/datasheet/packshots/clear-6','datasheet','system',1,1,0,130),
('nexled/datasheet/finishes','nexled/datasheet','finishes','nexled/datasheet/finishes','datasheet','system',1,0,1,20),
('nexled/datasheet/finishes/20deg','nexled/datasheet/finishes','20deg','nexled/datasheet/finishes/20deg','datasheet','system',1,1,0,10),
('nexled/datasheet/finishes/45deg','nexled/datasheet/finishes','45deg','nexled/datasheet/finishes/45deg','datasheet','system',1,1,0,20),
('nexled/datasheet/finishes/2x55deg-lf','nexled/datasheet/finishes','2x55deg-lf','nexled/datasheet/finishes/2x55deg-lf','datasheet','system',1,1,0,30),
('nexled/datasheet/finishes/40deg','nexled/datasheet/finishes','40deg','nexled/datasheet/finishes/40deg','datasheet','system',1,1,0,40),
('nexled/datasheet/finishes/frost','nexled/datasheet/finishes','frost','nexled/datasheet/finishes/frost','datasheet','system',1,1,0,50),
('nexled/datasheet/finishes/frostc','nexled/datasheet/finishes','frostc','nexled/datasheet/finishes/frostc','datasheet','system',1,1,0,60),
('nexled/datasheet/finishes/clear','nexled/datasheet/finishes','clear','nexled/datasheet/finishes/clear','datasheet','system',1,1,0,70),
('nexled/datasheet/finishes/generic','nexled/datasheet/finishes','generic','nexled/datasheet/finishes/generic','datasheet','system',1,1,0,80),
('nexled/datasheet/finishes/clear-1','nexled/datasheet/finishes','clear-1','nexled/datasheet/finishes/clear-1','datasheet','system',1,1,0,90),
('nexled/datasheet/finishes/clear-2','nexled/datasheet/finishes','clear-2','nexled/datasheet/finishes/clear-2','datasheet','system',1,1,0,100),
('nexled/datasheet/finishes/clear-4','nexled/datasheet/finishes','clear-4','nexled/datasheet/finishes/clear-4','datasheet','system',1,1,0,110),
('nexled/datasheet/finishes/clear-5','nexled/datasheet/finishes','clear-5','nexled/datasheet/finishes/clear-5','datasheet','system',1,1,0,120),
('nexled/datasheet/finishes/clear-6','nexled/datasheet/finishes','clear-6','nexled/datasheet/finishes/clear-6','datasheet','system',1,1,0,130),
('nexled/datasheet/drawings','nexled/datasheet','drawings','nexled/datasheet/drawings','datasheet','system',1,1,0,30),
('nexled/datasheet/diagrams','nexled/datasheet','diagrams','nexled/datasheet/diagrams','datasheet','system',1,1,1,40),
('nexled/datasheet/diagrams/inverted','nexled/datasheet/diagrams','inverted','nexled/datasheet/diagrams/inverted','datasheet','system',1,1,0,10),
('nexled/datasheet/mounting','nexled/datasheet','mounting','nexled/datasheet/mounting','datasheet','system',1,1,0,50),
('nexled/datasheet/connectors','nexled/datasheet','connectors','nexled/datasheet/connectors','datasheet','system',1,1,0,60),
('nexled/datasheet/temperatures','nexled/datasheet','temperatures','nexled/datasheet/temperatures','datasheet','system',1,1,0,70),
('nexled/datasheet/energy-labels','nexled/datasheet','energy-labels','nexled/datasheet/energy-labels','datasheet','system',1,1,1,80),
('nexled/datasheet/energy-labels/right','nexled/datasheet/energy-labels','right','nexled/datasheet/energy-labels/right','datasheet','system',1,1,0,10),
('nexled/datasheet/icons','nexled/datasheet','icons','nexled/datasheet/icons','datasheet','system',1,1,0,90),
('nexled/datasheet/logos','nexled/datasheet','logos','nexled/datasheet/logos','datasheet','system',1,1,0,100),
('nexled/datasheet/power-supplies','nexled/datasheet','power-supplies','nexled/datasheet/power-supplies','datasheet','system',1,1,0,110);
INSERT INTO `dam_folders` (`folder_id`,`parent_id`,`name`,`path`,`scope`,`kind`,`is_system`,`can_upload`,`can_create_children`,`sort_order`) VALUES
('nexled/media','nexled','media','nexled/media','media','system',1,0,1,20),
('nexled/media/products','nexled/media','products','nexled/media/products','media','system',1,1,1,10),
('nexled/media/lifestyle','nexled/media','lifestyle','nexled/media/lifestyle','media','system',1,1,0,20),
('nexled/media/datasheets','nexled/media','datasheets','nexled/media/datasheets','media','system',1,1,0,30),
('nexled/media/eprel','nexled/media','eprel','nexled/media/eprel','media','system',1,0,1,40),
('nexled/media/eprel/labels','nexled/media/eprel','labels','nexled/media/eprel/labels','media','system',1,1,0,10),
('nexled/media/eprel/fiches','nexled/media/eprel','fiches','nexled/media/eprel/fiches','media','system',1,1,0,20),
('nexled/media/brand','nexled/media','brand','nexled/media/brand','media','system',1,0,1,50),
('nexled/media/brand/logos','nexled/media/brand','logos','nexled/media/brand/logos','media','system',1,1,0,10),
('nexled/media/brand/guidelines','nexled/media/brand','guidelines','nexled/media/brand/guidelines','media','system',1,1,0,20),
('nexled/media/brand/presentations','nexled/media/brand','presentations','nexled/media/brand/presentations','media','system',1,1,0,30),
('nexled/media/store','nexled/media','store','nexled/media/store','media','system',1,0,1,60),
('nexled/media/store/hero','nexled/media/store','hero','nexled/media/store/hero','media','system',1,1,0,10),
('nexled/media/store/banners','nexled/media/store','banners','nexled/media/store/banners','media','system',1,1,0,20),
('nexled/media/store/categories','nexled/media/store','categories','nexled/media/store/categories','media','system',1,1,0,30),
('nexled/media/support','nexled/media','support','nexled/media/support','media','system',1,0,1,70),
('nexled/media/support/repair-guides','nexled/media/support','repair-guides','nexled/media/support/repair-guides','media','system',1,1,0,10),
('nexled/media/support/page-assets','nexled/media/support','page-assets','nexled/media/support/page-assets','media','system',1,1,0,20),
('nexled/media/website','nexled/media','website','nexled/media/website','media','system',1,0,1,80),
('nexled/media/website/hub','nexled/media/website','hub','nexled/media/website/hub','media','system',1,1,0,10),
('nexled/media/website/landing-pages','nexled/media/website','landing-pages','nexled/media/website/landing-pages','media','system',1,1,0,20);
